name: mvnrepository
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 0'
  workflow_dispatch:
jobs:
  read_mvn_repository:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Clone local repository locally
      uses: actions/checkout@v3
      with: 
        path: aadarchi-technology-detector
    - name: Clone TechEmpower benchmarks repository
      uses: actions/checkout@v3
      with:
        repository: TechEmpower/FrameworkBenchmarks
        ref: master
        path: FrameworkBenchmarks
        clean: false
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        cd aadarchi-technology-detector
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ensure browsers are installed
      run: cd aadarchi-technology-detector/ && python -m playwright install --with-deps
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 11
        cache: 'maven'
    - name: Ensure we have both directories locally
      run: tree -d -L 3
    - name: Run mvnrepository extraction code
    # xcfb is needed since we have some UI selector elements
      run: |
        xvfb-run python aadarchi-technology-detector/mvnrepository/extract_popular_mvnrepository_artifacts.py
        mkdir target
        mv aadarchi-technology-detector/mvnrepository/artifacts.json target/artifacts.json
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: reports
        FOLDER: target
        TARGET_DIR: mvnrepository
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MESSAGE: Updated mvnrepository infos
        COMMIT-NAME: 🤖 GitHub Action
        COMMIT_EMAIL: get_mvnrepository_infos.yaml@github.actions